development:
  adapter: postgresql
  encoding: unicode
  database: meetings-dev
  pool: 50

test:
  adapter: postgresql
  encoding: unicode
  database: meetings-test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: meetings-prod
  pool: 5
